### ISSUE TITLE
Please update (or specify) the versions of python and others.

### ISSUE THREAD

**Issue by yamake0222** [mbird1258/Audio-Decomposition#14]
Hi.
Thank you for releasing such a great tool!

I'm not that familiar with Python,
but I'm having trouble identifying the version of Python that satisfies the versions of each library specified in this file.
https://github.com/mbird1258/Audio-Decomposition/blob/556dc122d9f4bdafe096c942a225342d5e18f9dc/pyproject.toml

When I asked ChatGPT, it replied "3.7.X or later," but when I tried it, I got some error.
case1:
 python 3.12.7
 -> When installing numpy version 1.24.1, the following error occurs:
      "ModuleNotFoundError: No module named 'distutils'"
case2:
 python 3.7.20
 -> When I run Main.py, I get the following error on 
      https://github.com/mbird1258/Audio-Decomposition/blob/556dc122d9f4bdafe096c942a225342d5e18f9dc/Main.py#L199
     :
      "SyntaxError: invalid syntax"

Do the versions in pyproject.toml correspond to the actual situation?
Or, please tell me the version of Python you are using.

I'm not a native English speaker so I apologize if the sentences are strange.
Thanks.

**Comment by yamake0222** [comment]
For anyone facing the same issue,
I will share the information I got when I was able to run Main.py.
(I was able to get to it after creating this issue, but this is not necessarily the correct answer.)
```
> python -V
Python 3.10.11
> python -m pip freeze
beautifulsoup4==4.11.1
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
contourpy==1.3.1
cycler==0.12.1
fonttools==4.55.0
idna==3.10
kiwisolver==1.4.7
matplotlib==3.6.3
numpy==1.26.0
packaging==24.2
pillow==11.0.0
pycparser==2.22
pyparsing==3.2.0
python-dateutil==2.9.0.post0
requests==2.32.3
scipy==1.14.1
six==1.16.0
soundfile==0.12.1
soupsieve==2.6
urllib3==2.2.3
```

**Comment by mbird1258** [comment]
The reasons for the original issues were that Match Case syntax was only introduced in 3.10 and disutils removed in python 3.12. If you have to use an earlier version, you can replace match case with if elif statements, or with later versions install the latest version of numpy which doesn't use disutils.
