### ISSUE TITLE
Please add some documentation to the readme about how to install the dependencies

### ISSUE THREAD

**Issue by jhaungs** [mbird1258/Audio-Decomposition#6]
Since there's a .toml file, I tried "pip install ." but it doesn't work. FYI, wheel was already installed via brew.

> pip install .
Processing Audio-Decomposition
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout: ['In', 'PlayBack', 'InstrumentData', 'InstrumentAudioFiles'].

**Comment by mbird1258** [comment]
I’m not entirely sure why it’s not working, but if need be you can just manually install each one with pip install ____. (ex. pip install soundfile)

**Comment by jhaungs** [comment]
Thanks for the quick response. I figured it out. The bare "python" command
was running 3.12, but the pip install went to 3.11. I'll clean those up.
